### ISSUE TITLE
[Bug] Empty result for list of availabe colors, not working anymore after update

### ISSUE THREAD

**Issue by ceyhunnabiyev** [gusbemacbe/suru-plus-folders#11]
```
> suru-plus-folders -l --theme Suru++
List of available colors:



```

**Comment by gusbemacbe** [comment]
Hello @ceyhunnabiyev 

Did you rename the icons theme folder to Suru++?

**Comment by gusbemacbe** [comment]
I have just tested and there is really an error.

@SmartFinn, please, can you test the beta branch? I added "Suru++ 20" to the shell script, attempting to list the available colours, but the same errors still happens. I have upgraded icons theme and changed icons theme from "Suru++" to "Suru++ 20".

**Comment by SmartFinn** [comment]
@gusbemacbe I don't sure that a space in an icon theme name is valid.

**Comment by gusbemacbe** [comment]
`Suru++\ 20` or `'Suru++ 20'`.

**Comment by gusbemacbe** [comment]
The same bug happes:

```
[gusbemacbe@gusbemacbe-mac ~]$ suru-plus-folders -l --theme 'Suru++ 20'
List of available colors:



[gusbemacbe@gusbemacbe-mac ~]$ 
```

**Comment by gusbemacbe** [comment]
Ah, I got it. I will test renaming my icons theme.

**Comment by gusbemacbe** [comment]
Then I have changed `Suru++ 20` to `Suru++20`, and the same bug still happens.

**Comment by gusbemacbe** [comment]
I got it again, it is because I have changed from `scalable` to 64, based on Papirus, to rearrange and correct the misbuilding.

**Comment by gusbemacbe** [comment]
It worked now:

```
suru-plus-folders -l --theme Suru++\ 20
List of available colors:

   black
   blue
   bluegrey
   brown
   cyan
   green
   grey
   magenta
   orange
   red
   teal
   violet
   yellow
```

**Comment by gusbemacbe** [comment]
Finally:

```
suru-plus-folders -l --theme Suru++\ 20
List of available colors:

   black
 > blue
   bluegrey
   brown
   cyan
   green
   grey
   magenta
   orange
   red
   teal
   violet
   yellow
```

It is because of `scalable` due the upgrade I made in the icons theme, replacing for `64`.

**Comment by gusbemacbe** [comment]
@ceyhunnabiyev, it is fixed, please test it. Firstly uninstall and reinstall.

**Comment by ceyhunnabiyev** [comment]
@gusbemacbe , Thank you so much for the fast fix. It's worked..

**Comment by vaskark** [comment]
Hi. I'm experiencing the same problem on Ubuntu 19.04 and no list of colours is being produced. I've tried both:

suru-plus-folders -l --theme Suru++-Dark
suru-plus-folders -l --theme Suru++-Ubuntu

Any advice? Thanks.

**Comment by gusbemacbe** [comment]
Hi @vaskark 

Suru++ Dark is outdated, because it still uses the name `64` instead of `scalable`. I must upgrade it. While I do not upgrade, you can edit manually the `places` folders names, changing from `64` to `scalable`. 

I have just tested Suru++ Ubuntu, it appeared normally:

```
$ suru-plus-folders -l --theme Suru++-Ubuntu
List of available colors:

   aubergine
   blue
   bordeaux
   canonical
   cyan
   darkblue
   green
 > orange
   purple
   red
   vermillion
   yellow
```

**Comment by materemias** [comment]
@gusbemacbe I have installed Suru++-Dark, renamed `places/64` to `places/scalable` and I still have an empty list. do you have an idea how to go on?

**Comment by materemias** [comment]
nvm, I had 2 suru installs on in ~/.local and one in /usr. removing the local one did the trick
